#!/usr/bin/env bash
# ci_test_ubuntu.sh — local simulation of GitHub Actions ubuntu runner.
# Mirrors .github/workflows/ci.yml as closely as possible so we can
# reproduce CI failures on a developer machine without round-tripping
# to GitHub.
#
# Usage:
#   ci_test_ubuntu.sh                # full simulation (default)
#   ci_test_ubuntu.sh quick          # skip HTML report
#   ci_test_ubuntu.sh --rebuild      # force rebuild docker image
#
# Requirements: docker (Docker Desktop or docker engine).
# Tested with: Python 3.12 in python:3.12-slim (matches actions/setup-python@v5).
set -euo pipefail

# === Resolve script directory (works under PowerShell `bash` too) ===
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]:-$0}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
echo "================================================================"
echo "  auto-research-driver CI simulator"
echo "  repo: $REPO_ROOT"
echo "  mode: ${1:-full}"
echo "================================================================"

MODE="${1:-full}"
REBUILD=""
if [[ "${1:-}" == "--rebuild" ]]; then
    REBUILD="--no-cache"
    MODE="${2:-full}"
fi

# === Docker image (GitHub Actions ubuntu + Python 3.12) ===
IMAGE="python:3.12-slim"
CONTAINER_NAME="ard-ci-$$"

# === Mount points: read-write repo + isolated /tmp for test outputs ===
# We use :Z when SELinux is in play (Linux host); harmless on Windows / macOS.
DOCKER_RUN_OPTS=(
    --rm
    --name "$CONTAINER_NAME"
    -v "$REPO_ROOT:/work:rw,Z"
    -w /work
    -e PYTHONIOENCODING=utf-8
    -e PYTHONUTF8=1
    -e LANG=C.UTF-8
    -e LC_ALL=C.UTF-8
    -e CI=true
    -e GITHUB_ACTIONS=true
)

run_in_docker() {
    docker run "${DOCKER_RUN_OPTS[@]}" "$IMAGE" bash -c "$1"
}

# === preflight ===
if ! command -v docker >/dev/null 2>&1; then
    echo "FATAL: docker not in PATH" >&2
    exit 2
fi
if ! docker info >/dev/null 2>&1; then
    echo "FATAL: docker daemon not running (start Docker Desktop first)" >&2
    exit 2
fi

# === pre-build step (cached) ===
PRELUDE='set -e
echo "--- preflight ---"
python3 --version
pip --version
echo "--- ensure coverage installed ---"
pip install --quiet --disable-pip-version-check coverage
coverage --version
'

# === Mirror of Run CI step from ci.yml (run_tests.py) ===
RUN_TESTS_STEP='
set -e
cd /work
python3 ci/run_tests.py '"$MODE"'
'

# === Mirror of Upload coverage HTML (only if --full) ===
HTML_STEP=""
if [[ "$MODE" == "full" || "$MODE" == "html-only" ]]; then
    HTML_STEP='
echo "--- coverage html (already generated by run_tests.py) ---"
ls -la htmlcov/ 2>/dev/null | head -5 || echo "htmlcov/ missing"
'
fi

# === Concatenate the simulation ===
SIM="$PRELUDE"
SIM+="$RUN_TESTS_STEP"
if [[ -n "$HTML_STEP" ]]; then
    SIM+="$HTML_STEP"
fi
SIM+='
echo "--- SIMULATION COMPLETE ---"
'

# === Run ===
echo ">>> launching docker ($IMAGE)"
if [[ -n "$REBUILD" ]]; then
    echo ">>> (rebuild mode — pulling fresh image)"
    docker pull "$IMAGE" >/dev/null
fi

# Run docker, capture exit code, print everything
set +e
docker run "${DOCKER_RUN_OPTS[@]}" "$IMAGE" bash -c "$SIM"
DOCKER_RC=$?
set -e

echo
echo "================================================================"
if [[ $DOCKER_RC -eq 0 ]]; then
    echo "  SIMULATION PASSED  -  exit 0"
else
    echo "  SIMULATION FAILED  -  exit $DOCKER_RC"
fi
echo "  docker image: $IMAGE"
echo "  reproduce on GitHub:  push to main → Actions tab"
echo "================================================================"

exit $DOCKER_RC
